### ISSUE TITLE
(Error in treeprofile) KeyError: '2 node(s) founded for the ancestral genome 

### ISSUE THREAD

**Issue by maiumy** [DessimozLab/pyham#14]
I ran treeprofile for one specific tree and everything went well, but when I tried to run it for another tree I get this error. I already tried running the analysis again, but it didn't work. 
I can only assume that this is some with the new tree that I'm using, but I'm not sure what could be wrong with it.

The full error line is: 

`KeyError: '2 node(s) founded for the ancestral genome named centruroides_sculpturatus/parasteatoda_tepidariorum/limulus_polyphemus/ixodes_scapularis/dermacentor_silvarum/rhipicephalus_microplus/hyalomma_asiaticum/tetranychus_urticae/dermatophagoides_pteronyssinus/varroa_destructor/varroa_jacobsoni/dermanyssus_gallinae/daphnia_pulex/tribolium_castaneum'`

And my tree is: (((((centruroides_sculpturatus,parasteatoda_tepidariorum),limulus_polyphemus),(((ixodes_scapularis,(dermacentor_silvarum,(rhipicephalus_microplus,hyalomma_asiaticum))),(tetranychus_urticae,dermatophagoides_pteronyssinus)),((varroa_destructor,varroa_jacobsoni),dermanyssus_gallinae))),(daphnia_pulex,tribolium_castaneum)));

Does anyone know how I can solve this?
Thank you.

**Comment by gmartinezredondo** [comment]
I believe that the problem is that your tree has extra parentheses at the beginning and end. If you check the tree with http://etetoolkit.org/treeview/ you can see that there are two nodes at the root of the tree.
![imagen](https://user-images.githubusercontent.com/51078922/144718176-3e997373-541d-4e2c-bfd6-06c7b9e6254d.png)

Removing the extra parentheses, the problem should be solved.
This would be the fixed tree: ((((centruroides_sculpturatus,parasteatoda_tepidariorum),limulus_polyphemus),(((ixodes_scapularis,(dermacentor_silvarum,(rhipicephalus_microplus,hyalomma_asiaticum))),(tetranychus_urticae,dermatophagoides_pteronyssinus)),((varroa_destructor,varroa_jacobsoni),dermanyssus_gallinae))),(daphnia_pulex,tribolium_castaneum));

**Comment by maiumy** [comment]
Oh, that's right. I missed those extra parentheses.
Thank you!
